### ISSUE TITLE
support waterfox (Fx 56)

### ISSUE THREAD

**Issue by zhou13** [chenzhekl/unblock-youku-firefox#11]
Firefox 57+ no longer supports XUL so users like me still stay on waterfox, which is based on Fx 56.  I tested newest unlock youku but unforunately it does not work on Waterfox.  Could you support it?  Thanks!

**Comment by chenzhekl** [comment]
Probably no. Since we switched to a new proxy API (for alleviating a bug in Firefox) provided by Firefox 60+, it is a bit hard to support legacy versions.

Authors of Waterfox seemed to have a [plan](https://github.com/MrAlex94/Waterfox/issues/267#issuecomment-376351366) to keep in pace with Firefox 60. That would make it compatible with WebExtensions using new APIs (of course including us).

**Comment by zhou13** [comment]
Thanks for your explanation.  For now I will probably use chronium or Fx60+.
